### Obtener todas las peliculas
GET http://localhost:3000/movies

### Obtener pelicula por id
GET http://localhost:3000/movies/6668ed55db5f9eb1793db66b
# 6668cf61e77b31226170f07d
# fb2d1832-2477-11ef-b3e8-a434d9b97a1c 


### Obtener peliculas por generos
GET http://localhost:3000/movies?genre=adventure

### Crear nueva pelicula
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Inception",
  "year": 2011,
  "director": "Christopher Nolan",
  "duration": 148,
  "poster": "https://m.media-amazon.com/images/I/912AErFSBHL._AC_UF894,1000_QL80_.jpg",
  "genre": ["Action", "Sci-Fi"],
  "rate": 8.8
}

### Actualizar pelicula

PATCH http://localhost:3000/movies/66690417c9b2671dbe5cf798
Content-Type: application/json

{
  "title": "El señor de la noche",
  "rate": 9.9,
  "genre": ["Action", "Sci-Fi", "Romance"]
}

### Elimina una pelicula
DELETE  http://localhost:3000/movies/66690417c9b2671dbe5cf798

